In [3]:
#1
import numpy as np
a= np.array([10, 20, 30, 40, 50])  
print("Original array:", a)
added=a+2
print(added)
multi=a*3
print(multi)
divide=a/2
print(divide)



Original array: [10 20 30 40 50]
[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [5]:
#2a
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]  
print("Reversed array:", reversed_arr)


Reversed array: [5 4 6 3 2 1]


In [13]:
#2b
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
unique, counts = np.unique(x, return_counts=True)
most_frequent = unique[np.argmax(counts)]
indices_x = np.where(x == most_frequent)

print("Most frequent value in x:", most_frequent)
print("Indices of the most frequent value in x:", indices_x)

Most frequent value in x: 1
Indices of the most frequent value in x: (array([0, 5, 7, 8, 9], dtype=int64),)


In [15]:
#2b
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
u,c=np.unique(y,return_counts=True)
f=unique[np.argmax(c)]
indices_y= np.where(y == f)

print("Most frequent value in y:", f)
print("Indices of the most frequent value in y:", indices_y)


Most frequent value in y: 1
Indices of the most frequent value in y: (array([0, 1, 2], dtype=int64),)


In [19]:
#3
import numpy as np
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])


20
70


In [27]:
import numpy as np
Manya = np.linspace(10, 100, 25)  
print( Manya)
print("Dimensions of the array:", Manya.ndim)
print("Shape of the array:", Manya.shape)

print("Total number of elements:", Manya.size)
print("Data type of elements:", Manya.dtype)

print("Total bytes consumed by the array:", Manya.nbytes)

print("Transposed arry:\n", Manya.reshape(25, 1))
print('hello')
print("using t:", Manya.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total number of elements: 25
Data type of elements: float64
Total bytes consumed by the array: 200
Transposed arry:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
hello
using t: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [42]:
#5
import numpy as np
ucs420_Manya = np.array([[10, 20, 30, 40], 
                             [50, 60, 70, 80], 
                             [90, 15, 20, 35]])
print( ucs420_Manya)
print(np.mean(ucs420_Manya))
print(np.median(ucs420_Manya))

print(np.unique(ucs420_Manya))
print(np.min(ucs420_Manya))
print(np.max(ucs420_Manya))

print(ucs420_Manya.reshape(4,3))
print(np.resize(ucs420_Manya,(2,3)))

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
43.333333333333336
37.5
[10 15 20 30 35 40 50 60 70 80 90]
10
90
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
