In [1]:
import numpy as np
gfg=np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') 
allsum=np.sum(gfg)
rowssum=np.sum(gfg,axis=1)
colssum=np.sum(gfg,axis=0)
print(allsum)
print(rowssum)
print(colssum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [3]:
import numpy as np    
a = np.array([10, 52, 62, 16, 16, 54, 453]) 
sorted_array=np.sort(a)
sorted_indices = np.argsort(a)
smallest_4 = np.sort(a)[:4] 
largest_5 = np.sort(a)[-5:] 
print(sorted_array)
print(sorted_indices)
print(smallest_4)
print(largest_5)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [5]:
import numpy as np  
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])   
integers = array[array == array.astype(int)]   
floats = array[array != array.astype(int)]  
print(integers)
print(floats)

[1. 2. 3. 2.]
[1.2 2.2]


In [6]:
import numpy as np  
X = ord('M') + ord('J')   
sales = np.array([X, X+50, X+100, X+150, X+200])  
print("Sales dataset:", sales)  
tax_rate = ((X % 5) + 5) / 100
tax_amount = sales * tax_rate  
print(tax_rate)
print(tax_amount)
discount_rate = np.where(sales < X+100, 0.05, 0.10)  
discount_amount = sales * discount_rate
adjusted_sales = sales - discount_amount


print("Discount Rate:", discount_rate)
print("Discount Amount:", discount_amount)
print("Adjusted Sales:", adjusted_sales)

weeks = 3
sales_matrix = np.tile(sales, (weeks, 1)) 
print("Initial Sales Matrix:\n", sales_matrix)

weekly_multipliers = (1.02) ** np.arange(weeks).reshape(weeks, 1)  # [1, 1.02, 1.04]
adjusted_sales_matrix = sales_matrix * weekly_multipliers
print("Sales Matrix after 2% Weekly Increase:\n", np.round(adjusted_sales_matrix, 2))  

Sales dataset: [151 201 251 301 351]
0.06
[ 9.06 12.06 15.06 18.06 21.06]
Discount Rate: [0.05 0.05 0.1  0.1  0.1 ]
Discount Amount: [ 7.55 10.05 25.1  30.1  35.1 ]
Adjusted Sales: [143.45 190.95 225.9  270.9  315.9 ]
Initial Sales Matrix:
 [[151 201 251 301 351]
 [151 201 251 301 351]
 [151 201 251 301 351]]
Sales Matrix after 2% Weekly Increase:
 [[151.   201.   251.   301.   351.  ]
 [154.02 205.02 256.02 307.02 358.02]
 [157.1  209.12 261.14 313.16 365.18]]
